# Generated by Django 4.0.6 on 2022-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_date', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=1000)),
                ('Fullname', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=300)),
            ],
        ),
    ]
